function [options] = TrainOptionsODF(InitialLearnRate, ...
            MaxEpochs,MiniBatchSize,Shuffle)
options = trainingOptions('sgdm', ...
      'InitialLearnRate', InitialLearnRate ,...
      'LearnRateSchedule', 'none' ,... %'piecewise'
      'LearnRateDropFactor', 0.2000 ,...
      'LearnRateDropPeriod', 5 ,...
      'MaxEpochs', MaxEpochs ,...
      'MiniBatchSize', MiniBatchSize ,...
      'Verbose', 1 ,...    %Indicator to display training progress
      'VerboseFrequency' , 50 ,...
      'ValidationData', [] ,...
      'Shuffle', Shuffle ,...  %Option for data shuffling
      'Plots', 'training-progress' );